# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='mis_imagenes'),
        ),
    ]
