# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_auto_20170912_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['id'], 'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
